### PR TITLE
Display modes

### PR DESCRIPTION
**Pull request by Yanpas**
Screenshot:

Sources:
[source.zip](https://github.com/linuxmint/libreoffice-style-mint/files/233463/source.zip)

### CODE REVIEW

**Comment by Yanpas** [comment]
I'm not sure whether dotted lines are good looking. BTW I absolutely don't mind editing my source files

**Comment by clefebvre** [comment]
@Yanpas I think it looks nice. I'm not sure orange is the best highlighting color (I'm biaised, I usually prefer green or shades of grey :)).

**Comment by Yanpas** [comment]
@clefebvre I've updated both commits :) BTW github supports commit squashing, so I think it's ok that both my PR's contain two commits.

**Comment by clefebvre** [comment]
Thanks @Yanpas

**Comment by clefebvre** [comment]
@Yanpas it could be on my side, but I'm testing the theme with LO 5.1.2.2 in a Mint 18 ALPHA ISO here and none of the icons are loading.

**Comment by clefebvre** [comment]
They fail to load with http://packages.linuxmint.com/pool/main/libr/libreoffice-style-mint/libreoffice-style-mint_5.1+2_all.deb.

They load OK with http://mirrors.kernel.org/ubuntu/pool/universe/libr/libreoffice/libreoffice-style-human_5.1.2-0ubuntu1_all.deb.

**Comment by clefebvre** [comment]
I see this when launching LO from terminal:

(soffice:16197): Gdk-WARNING **: gdk_window_set_icon_list: icons too large

(soffice:16197): Gdk-WARNING **: gdk_window_set_icon_list: icons too large

*\* (soffice:16197): WARNING **: Invalidate all children called

**Comment by Yanpas** [comment]
I get the same warnings on LM17.3 and LO 5.1.2, but everything works.
libreoffice-style-human package does not contain such icons.

Have you tested LO 5.1.x on LM17.x distro? I guess gtk update have broken something.

I've followed tango icons theme namings/conventions etc. I guess if Breeze and Tango icons do not work, then something wrong with LO/GTK. You may find them in `ppa:libreoffice`:
`libreoffice-style-tango libreoffice-style-breeze`

**Comment by Yanpas** [comment]
@clefebvre Images from your package do not work at all, cause you have placed them in images_human directory


I've repacked the archive and no everything works on Xubuntu 16.04

**Comment by clefebvre** [comment]
ah.. I didn't see that when extracting it, well spotted.

I'll check the packaging to see why it's doing that.

**Pull request merged**
